# Name of the application
APPLICATION = hello-world

# Default target board
BOARD ?= nucleo-f746zg

USEMODULE += xtimer

# Path to the RIOT base directory
RIOTBASE ?= $(CURDIR)/../../RIOT

# Include all build system logic for building the application
include $(RIOTBASE)/Makefile.include