# Name of the application
APPLICATION = managing-sensors

USEMODULE += lis3mdl
USEMODULE += xtimer
USEMODULE += shell
USEMODULE += lps22hb
USEMODULE += hts221

# Path to the RIOT base directory
RIOTBASE ?= $(CURDIR)/../../../RIOT

include $(RIOTBASE)/Makefile.include