# Name of the application
APPLICATION = AT-command

# Default target board
BOARD ?= nucleo-f746zg

USEMODULE += at
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += xtimer

# Path to the RIOT base directory
RIOTBASE ?= $(CURDIR)/../../RIOT

# Include all build system logic for building the application
include $(RIOTBASE)/Makefile.include